#tuto_album_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: TutoAlbumBundle:Default:index }

tuto_album:
    resource: "@TutoAlbumBundle/Controller/AlbumController.php"
    type:     annotation
