parameters:
#    tuto_album.example.class: Tuto\AlbumBundle\Example

services:
#    tuto_album.example:
#        class: %tuto_album.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
