parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     sf2tutorial
    database_user:     sf2tuto
    database_password: sf2tuto

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            b818f56b8eff5074e3e1eb36e3325c85b2d5d72c
